

export const  StaticDataCards = [
    { id: "kw9wXRLL", name: "Humidity", icon: require('../../assets/experienceIcons/humidite.png'), color:"#C2FEFE" },
    { id: "FLbSCHLE", name: "Temperature", icon: require('../../assets/experienceIcons/temperature.png'), color:"#FD9093" },
    { id: "IWpMYRxk", name: "Contact", icon: require('../../assets/experienceIcons/contact.png'), color:"#C3FFDD" },
    { id: "JSaaUpuw", name: "Gas", icon: require('../../assets/experienceIcons/gaz.png'), color:"#E4C2F6" },
    { id: "0C3g30jn", name: "Orientation", icon: require('../../assets/experienceIcons/orientation.png'), color:"#C2CAFC" },
    { id: "Od6mqK4U", name: "Force", icon: require('../../assets/experienceIcons/force.png'), color:"#CFF380" },
    { id: "1sXGfNFf", name: "Brightness", icon: require('../../assets/experienceIcons/luminosite.png'), color:"#C2FEFE" },
    { id: "vzJOaUir", name: "Elevation", icon: require('../../assets/experienceIcons/elevation.png'), color:"#82B4DD" },
    { id: "uICSlYX3", name: "Color", icon: require('../../assets/experienceIcons/color.png'), color:"#8CE7D4" },
    { id: "TKYslspt", name: "Position", icon: require('../../assets/experienceIcons/position.png'), color:"#C2CAFC" },
    { id: "pciCeBnr", name: "Proximity", icon: require('../../assets/experienceIcons/proximite.png'), color:"#C2FEFE" },
    { id: "kFkGmGVr", name: "Sound", icon: require('../../assets/experienceIcons/son.png'), color:"#E9CF36" },
    { id: "grCRAm9n", name: "Vibration", icon: require('../../assets/experienceIcons/vibration.png'), color:"#82B4DD" },
    { id: "UJ0jB8y0", name: "Speed", icon: require('../../assets/experienceIcons/vitesse.png'), color:"#8CE7D4" },
];

['5wRTxXgE', 'qKji7Yt0', 'FiVrz3Ir', 'NbyrtZr7', 'k1OCh38l', 'iXAufTOl', 'wi4mFHUy', 'ddquBRSg', 'v2RHqG3O', 'ZHggKd6u', 'SbOrLTw0', '7RUCIR5X']

export const StaticExperiences = [
    { 
      id: "5wRTxXgE",
      name: "Trust", 
      color:"#FFF",
      definition: "Confiance: La confiance est le sentiment de fiabilité et de crédibilité envers quelqu'un ou quelque chose.",
      experience: "Trust",  
    },
    { 
      id: "qKji7Yt0",
      name: "Comfort", 
      color:"#FFF",
      definition: "Confort: Le confort représente le sentiment de bien-être et de détente physique ou psychologique.",
      experience: "Comfort",  
    },
    { 
      id: "FiVrz3Ir",
      name: "Fear", 
      color:"#FFF",
      definition: "Peur: La peur est une émotion ressentie face à une menace, un danger ou quelque chose d'inconnu.",
      experience: "Fear",
    },
    { id: "NbyrtZr7",
      name: "Control", 
      color:"#FFF",
      definition: "Contrôle: Le contrôle implique le pouvoir de diriger, réguler ou influencer une situation ou un événement.",
      experience: "Control",
    },
    { id: "k1OCh38l",
      name: "Effi\nciency", 
      color:"#FFF",
      definition: "Efficacité: L'efficacité est la capacité à atteindre un objectif ou produire un résultat avec le minimum de ressources utilisées.",
      experience: "Efficiency",
    },
    { id: "iXAufTOl",
      name: "Learn\nability", 
      color:"#FFF",
      definition: "Facilité d'apprentissage: La facilité d'apprentissage désigne la facilité avec laquelle on peut acquérir de nouvelles compétences ou connaissances.",
      experience: "Learnability",
    },
    { id: "wi4mFHUy",
      name: "Ease of use", 
      color:"#FFF",
      definition: "Facilité d'utilisation: La facilité d'utilisation indique la simplicité et la praticité d'utilisation d'un produit ou d'un système.",
      experience: "Ease of use",
    },
    { id: "ddquBRSg",
      name: "Stress", 
      color:"#FFF",
      definition: "Stress: Le stress est une réponse physique ou émotionnelle à une pression ou à une situation difficile.",
      experience: "Stress",
    },
    { id: "v2RHqG3O",
      name: "Intuiti\nvity", 
      color:"#FFF",
      definition: "Intuitivité: L'intuitivité se rapporte à la facilité de compréhension ou d'utilisation d'une chose sans besoin d'explications complexes.",
      experience: "Intuitivity",
    },
    { id: "ZHggKd6u",
      name: "Perfor\nmance", 
      color:"#FFF",
      definition: "Performance: La performance représente la qualité d'exécution ou de fonctionnement d'une personne, d'un produit ou d'un système.",
      experience: "Performance",
    },
    { id: "SbOrLTw0",
      name: "Relia\nbility", 
      color:"#FFF",
      definition: "Fiabilité: La fiabilité est la capacité d'une personne ou d'un objet à maintenir des standards élevés de qualité et de performance de manière consistante.",
      experience: "Reliability",
    },
    { id: "7RUCIR5X",
      name: "Safety", 
      color:"#FFF",
      definition: "Sécurité: La sécurité est l'état de protection contre les dangers, les risques ou les menaces pour éviter les dommages ou les blessures.",
      experience: "Safety",
    },
    
];